# Generated by Django 5.0.6 on 2026-06-27 16:48

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_summary', models.TextField(blank=True)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'diagnostics_debug_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_cause', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('detected_stack', models.JSONField(default=list)),
                ('detected_cloud_provider', models.CharField(blank=True, max_length=100)),
                ('explanation', models.TextField()),
                ('evidence_json', models.JSONField(default=list)),
                ('recommended_fix', models.TextField()),
                ('commands_json', models.JSONField(default=list)),
                ('verification_checklist_json', models.JSONField(default=list)),
                ('missing_information_json', models.JSONField(default=list)),
                ('possible_risks_json', models.JSONField(default=list)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debug_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.debugsession')),
            ],
            options={
                'db_table': 'diagnostics_diagnosis_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('stack', models.CharField(blank=True, max_length=255)),
                ('cloud_provider', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostics_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='debugsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='diagnostics.project'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('line_count', models.PositiveIntegerField()),
                ('redaction_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('debug_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='diagnostics.debugsession')),
            ],
            options={
                'db_table': 'diagnostics_uploaded_file',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('confidence_hint', models.FloatField()),
                ('matched_pattern', models.CharField(blank=True, max_length=255)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debug_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_issues', to='diagnostics.debugsession')),
            ],
            options={
                'db_table': 'diagnostics_detected_issue',
                'ordering': ['-confidence_hint'],
                'indexes': [models.Index(fields=['debug_session'], name='diagnostics_debug_s_be5255_idx'), models.Index(fields=['issue_type'], name='diagnostics_issue_t_0f1a37_idx'), models.Index(fields=['severity'], name='diagnostics_severit_7cd1c7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='detectedissue',
            constraint=models.CheckConstraint(check=models.Q(('confidence_hint__gte', 0), ('confidence_hint__lt', 1)), name='detected_issue_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='detectedissue',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['low', 'medium', 'high'])), name='detected_issue_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='diagnosisreport',
            constraint=models.CheckConstraint(check=models.Q(('confidence_score__gte', 0), ('confidence_score__lt', 1)), name='report_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='diagnosisreport',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['low', 'medium', 'high'])), name='report_severity_valid'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='diagnostics_user_id_143712_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), name='uniq_project_name_per_user_ci'),
        ),
        migrations.AddIndex(
            model_name='debugsession',
            index=models.Index(fields=['project', '-created_at'], name='diagnostics_project_a8260a_idx'),
        ),
        migrations.AddIndex(
            model_name='debugsession',
            index=models.Index(fields=['status'], name='diagnostics_status_e53bb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='debugsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'analyzing', 'completed', 'failed'])), name='debug_session_status_valid'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['debug_session', 'uploaded_at'], name='diagnostics_debug_s_9fb739_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('debug_session', 'content_sha256'), name='uniq_upload_content_per_session'),
        ),
    ]
