# Generated by Django 5.0.6 on 2026-06-29 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('zip', 'ZIP'), ('folder', 'Folder')], max_length=20)),
                ('source_name', models.CharField(max_length=500)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('file_tree', models.JSONField(default=list)),
                ('files_checked', models.JSONField(default=list)),
                ('files_ignored', models.JSONField(default=list)),
                ('detected_stack', models.JSONField(default=list)),
                ('detected_target', models.CharField(blank=True, max_length=100)),
                ('total_files', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'diagnostics_project_import',
            },
        ),
        migrations.CreateModel(
            name='ReadinessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness_score', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('detected_stack', models.JSONField(default=list)),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('zip', 'ZIP'), ('folder', 'Folder')], max_length=20)),
                ('deployment_target', models.CharField(blank=True, max_length=100)),
                ('blocking_issues_json', models.JSONField(default=list)),
                ('warnings_json', models.JSONField(default=list)),
                ('improvements_json', models.JSONField(default=list)),
                ('passed_checks_json', models.JSONField(default=list)),
                ('recommendations_json', models.JSONField(default=list)),
                ('evidence_json', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('patch_suggestions_json', models.JSONField(default=list)),
                ('action_plan_json', models.JSONField(default=list)),
                ('ai_insights_json', models.JSONField(default=list)),
                ('confidence_note', models.TextField(blank=True)),
                ('ai_used', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diagnostics_readiness_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='debugsession',
            name='kind',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('readiness', 'Readiness')], default='diagnosis', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='debugsession',
            constraint=models.CheckConstraint(check=models.Q(('kind__in', ['diagnosis', 'readiness'])), name='debug_session_kind_valid'),
        ),
        migrations.AddField(
            model_name='projectimport',
            name='debug_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_import', to='diagnostics.debugsession'),
        ),
        migrations.AddField(
            model_name='readinessreport',
            name='debug_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_report', to='diagnostics.debugsession'),
        ),
        migrations.AddConstraint(
            model_name='readinessreport',
            constraint=models.CheckConstraint(check=models.Q(('readiness_score__lte', 100)), name='readiness_report_score_max'),
        ),
        migrations.AddConstraint(
            model_name='readinessreport',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['low', 'medium', 'high'])), name='readiness_report_severity_valid'),
        ),
    ]
